<?php

/**
 * Galleries
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Galleries extends BaseGalleries
{
    public function addGallery(array $data) {
        $errors = $this->__validate($data);
        if ($errors['error_flag']) {
            return $errors;
        } else {
            $g = new Galleries();
            $g->image = $errors['image'];
            $g->project_name = $data['project_name'];
            $g->year_execution = $data['year_execution'];
            $g->category_id = $data['category_id'];
            $g->my_role = $data['my_role'];
            $g->created_at = date('ymdHis');
            $g->save();
        }
    }
    
    public function updateGallery(array $data) {
        $errors = $this->__validate($data);
        if ($errors['error_flag']) {
            return $errors;
        } else {
            Doctrine_Query::create()
                    ->update('Galleries g')
                    ->set('g.image', '?', $errors['image'])
                    ->set('g.project_name', '?', $data['project_name'])
                    ->set('g.year_execution', '?', $data['year_execution'])
                    ->set('g.category_id', '?', $data['category_id'])
                    ->set('g.my_role', '?', $data['my_role'])                    
                    ->set('g.updated_at', '?', date('ymdHis'))
                    ->where('g.id=?', $data['gallery_id'])
                    ->execute();
        }
    }
    
    public function deleteGallery($gallery_id) {
        Doctrine_Query::create()
                ->update('Galleries g')
                ->set('g.deleted', '?', true)
                ->where('g.id=?', $gallery_id)
                ->execute();
    }

    private function __validate($data) {
        $errors = array();
        $error_flag = false;

        if (!required($data['project_name'])) {
            $errors['project_name'] = 'Please write in project name';
            $error_flag = true;
        }
        if (!required($data['year_execution'])) {
            $errors['year_execution'] = 'Please write in year of execution';
            $error_flag = true;
        }
        if (!required($data['my_role'])) {
            $errors['my_role'] = 'Please write in my role';
            $error_flag = true;
        }
        
        if (isset($data['gallery_id'])) {
            if (isset($_FILES['userfile']) && !empty($_FILES['userfile']['name'])) {
                $upload_data = upload_file('gallery', array('jpg|png|jpeg|gif'), '2028');
                if ($upload_data['error_flag']) {
                    $errors['image'] = $upload_data['errors'];
                    $error_flag = true;
                } else {
                    $errors['image'] = $upload_data['upload_data']['file_name'];
                }
            } else if ($data['image']) {
                $errors['image'] = $data['image'];
            }
        } else {
            $upload_data = upload_file('gallery', array('jpg|png|jpeg|gif'), '2028');
            if ($upload_data['error_flag']) {
                $errors['image'] = $upload_data['errors'];
                $error_flag = true;
            } else {
                $errors['image'] = $upload_data['upload_data']['file_name'];
            }
        }


        $errors['error_flag'] = $error_flag;

        return $errors;
    }
}