<?php

/**
 * GalleryCategoriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GalleryCategoriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GalleryCategoriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GalleryCategories');
    }
    
    public static function getAllCategories() {
        return Doctrine_Query::create()
                ->select('gc.*')
                ->from('GalleryCategories gc')
                ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                ->execute();
    }
}