<?php

/**
 * GalleriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GalleriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GalleriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Galleries');
    }
    
    public static function getOne($gallery_id) {
        return Doctrine_Query::create()
                ->select('g.*')
                ->from('Galleries g')
                ->where('g.id=?', $gallery_id)
                ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                ->fetchOne();
    }
    
    public static function getAllGalleries() {
        return Doctrine_Query::create()
                ->select('g.*, c.name')
                ->from('Galleries g, g.GalleryCategories c')
                ->where('g.deleted=0')
                ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                ->execute();
    }
}