<?php

/**
 * Portfolios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Portfolios extends BasePortfolios {

    public function add_portfolio(array $data) {
        $errors = $this->__validate($data);
        if ($errors['error_flag']) {
            return $errors;
        } else {
            $p = new Portfolios();
            $p->image = $errors['image'];
            $p->title = $data['title'];
            $p->category_id = $data['category_id'];
            $p->role_id = $data['role_id'];
            $p->location = $data['location'];
            $p->date = $data['date'];
            $p->description = $data['description'];
            $p->created_at = date('ymdHis');
            $p->save();
        }
    }
    
    public function updatePortfolio(array $data) {
        $errors = $this->__validate($data);
        if ($errors['error_flag']) {
            return $errors;
        } else {
            Doctrine_Query::create()
                    ->update('Portfolios p')
                    ->set('p.image', '?', $errors['image'])
                    ->set('p.title', '?', $data['title'])
                    ->set('p.category_id', '?', $data['category_id'])
                    ->set('p.role_id', '?', $data['role_id'])
                    ->set('p.location', '?', $data['location'])
                    ->set('p.date', '?', $data['date'])
                    ->set('p.description', '?', $data['description'])
                    ->set('p.updated_at', '?', date('ymdHis'))
                    ->where('p.id=?', $data['portfolio_id'])
                    ->execute();
        }
    }
    
    public function deletePortfolio($portfolio_id) {
        Doctrine_Query::create()
                ->update('Portfolios p')
                ->set('p.deleted', '?', true)
                ->where('p.id=?', $portfolio_id)
                ->execute();
    }

    private function __validate($data) {
        $errors = array();
        $error_flag = false;

        if (!required($data['title'])) {
            $errors['title'] = 'Please write in title';
            $error_flag = true;
        }
        if (!required($data['date'])) {
            $errors['date'] = 'Please write in date';
            $error_flag = true;
        }
        if (!required($data['location'])) {
            $errors['location'] = 'Please write in location';
            $error_flag = true;
        }
        if (!required($data['description'])) {
            $errors['description'] = 'Please write in description';
            $error_flag = true;
        }

        if (isset($data['portfolio_id'])) {
            if (isset($_FILES['userfile']) && !empty($_FILES['userfile']['name'])) {
                $upload_data = upload_file('portfolio', array('jpg|png|jpeg|gif'), '2028');
                if ($upload_data['error_flag']) {
                    $errors['image'] = $upload_data['errors'];
                    $error_flag = true;
                } else {
                    $errors['image'] = $upload_data['upload_data']['file_name'];
                }
            } else if ($data['image']) {
                $errors['image'] = $data['image'];
            }
        } else {
            $upload_data = upload_file('portfolio', array('jpg|png|jpeg|gif'), '2028');
            if ($upload_data['error_flag']) {
                $errors['image'] = $upload_data['errors'];
                $error_flag = true;
            } else {
                $errors['image'] = $upload_data['upload_data']['file_name'];
            }
        }


        $errors['error_flag'] = $error_flag;

        return $errors;
    }

}
