<?php

/**
 * PortfoliosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PortfoliosTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object PortfoliosTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Portfolios');
    }

    public static function getOne($portfolio_id) {
        return Doctrine_Query::create()
                        ->select('p.*')
                        ->from('Portfolios p')
                        ->where('p.id =?', $portfolio_id)
                        ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                        ->fetchOne();
    }

    public static function getAll() {
        return Doctrine_Query::create()
                        ->select('p.*')
                        ->from('Portfolios p')
                        ->where('p.deleted =0')
                        ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                        ->execute();
    }

    public static function getPortfoliosByFilters($category_id = '', $role_id = '', $from = '', $to = '') {
        $q = Doctrine_Query::create()
                ->select('p.*')
                ->from('Portfolios p')
                ->where('p.deleted =0');
        if (isset($category_id) && $category_id) {
            $q = $q->andWhere('p.category_id =?', $category_id);
        }
        if (isset($role_id) && $role_id) {
            $q = $q->andWhere('p.role_id =?', $role_id);
        }
        if (isset($from) && $from) {
            $q = $q->andWhere('SUBSTRING(p.date,1,4) >=?', $from);
        }
        if (isset($to) && $to) {
            $q = $q->andWhere('SUBSTRING(p.date,1,4) <=?', $to);
        }
        $q = $q->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                ->execute();
        
        return $q;
    }

}
