<?php

/**
 * StaticPages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class StaticPages extends BaseStaticPages {

    public function updatePage($page_id, $content) {
        $errors = $this->__validate($content);
        
        if ($errors['error_flag']) {
            return $errors;
        } else {
            Doctrine_Query::create()
                    ->update('StaticPages sp')
                    ->set('sp.content', '?', $content)
                    ->set('sp.updated_at', '?', date('ymdHis'))
                    ->where('sp.page_id =?', $page_id)
                    ->execute();
            
            return $errors;
        }
    }

    private function __validate($content) {
        $errors = array();
        $error_flag = false;

        if (!required($content)) {
            $errors['content'] = 'Please write in content field';
            $error_flag = true;
        }

        $errors['error_flag'] = $error_flag;

        return $errors;
    }

}
